spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/olimpdb
    username: postgres
    password: 12345678
    driver-class-name: org.postgresql.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: enverablyamitov2003@gmail.com
    password: dgyn rwti vemw wovy
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true





  #  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect



  liquibase:
    change-log: classpath:liquibase/db.changelog.yaml
    enabled: true
    default-schema: public

security:
  jwt:
    secret: YXNkYXNkYXNkYXNmc2RmbXNhZGtvaGZpb3NkdWpmb2RzamZrZGZqT0lBREZKRElPU0pGRElPU0pG
    access:  21600000
    refresh: 2592000000


