name: Deploy
env:
    SUPER_SECRET: ${{ secrets.SSH_KEY }}
    PASS: ${{ secrets.PASS }}
    CI: false
on:
    push:
        branches:
            - master

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            # Клонирование репозитория
            - uses: actions/checkout@v2

            # Установка зависимостей и сборка проекта
            - run: npm ci
            - run: npm run build

            - name: Install sshpass
              run: sudo apt-get update && sudo apt-get install -y sshpass

            # Настройка SSH и использование rsync для деплоя
            - run: mkdir -p ~/.ssh
            - run: echo "$SUPER_SECRET" | tr -d '\r' > ~/.ssh/id_key
            - run: chmod 600 ~/.ssh/id_key
            
            - name: Deploy with SCP
              run: sshpass -p "$PASS" scp -P 52284 -o StrictHostKeyChecking=no -r ./build/* user@185.186.235.12:/home/user/front-end-olympus/
           
