name: Deploy
env:
    SUPER_SECRET: ${{ secrets.SSH_KEY }}
    CI: false
on:
    push:
        branches:
            - master

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            # Клонирование репозитория
            - uses: actions/checkout@v2

            # Установка зависимостей и сборка проекта
            - run: npm ci
            #- run: npm run build

            # Настройка SSH и использование rsync для деплоя
            - run: mkdir -p ~/.ssh
            - run: echo "$SUPER_SECRET" | tr -d '\r' > ~/.ssh/id_key
            - run: chmod 600 ~/.ssh/id_key
            - run: ssh -o StrictHostKeyChecking=no -i $HOME/.ssh/id_key -p 22 contest@51.250.41.208 "echo 'Connected'"
            - run:
                  rsync -e "ssh -p 22 -i $HOME/.ssh/id_key -o StrictHostKeyChecking=no" \
                  --archive --compress --delete -r ./build/ \
                  contest@51.250.41.208:/home/contest/olympus-front-end/
